POST http://localhost:8800/api/movies
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZGEwMzE1ZTZjOTlhYjRlMDVkODRlNyIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY0MTY4MDcwNCwiZXhwIjoxNjQxOTM5OTA0fQ.jSUb4CVMLCCYVPQQqemyvypwflL92Qs0whAFg5V0uyo

{
    "title":"Idiot11",
    "desc":"test desc",
    "img":"https://images.cinemaexpress.com/uploads/user/imagelibrary/2020/5/1/original/3_Idiots.PNG",
    "imgTitle":"https://image.pngaaa.com/499/3423499-middle.png",
    "trailer":"https://www.youtube.com/watch?v=K0eDlFX9GMc",
    "video":"https://www.youtube.com/watch?v=QaUaLruRP6Y",
    "year":"2010",
    "limit":10,
    "genre":"comedy"
}
