POST http://localhost:8800/api/auth/register
Content-Type: application/json

{
    "username": "Quavdvvddnvg Bach",
    "email": "quanvvdbddavfvch@gmail.com",
    "password": "123456789",
    "isAdmin": "true"
}