GET  http://localhost:8800/api/movies/random
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZGEwYjQxOTQ4YWU3ZTc0Mzk3MzQ5MSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2NDIwMDA0MzcsImV4cCI6MTY0MjI1OTYzN30.eOvstnL6dwC-9E4Pc4akxCik7vG91uOSI6RSo9Ck4t8